### PR TITLE
Project restructured

### LINKED ISSUE #5: Improve Folder Structure
Components should be in folder of compoenents and pages should be pages folder.
I will work on it

### PR DESCRIPTION
**Pull request by Chandraprakash-Darji**
fixes #5 #3
Changes that are Made:

Navbar and Bottom arrows are in the components directory.
/About, /Blog, /Contact, /Intro, and /Project are in the pages directory.
All the images in /public directory.
Navbar is only included in App because it is shared with the whole app it will remain the same.
Added favicon to the Website.
Changed the render() function in main.jsx according to react 18.
imported CSS only to App no need to include it in every file.
Instead of using navigate() I changed to Link component.
Home page is proper responsive
Navlink has now active Link view
Navbar is reponsive and centered to layout
Navbar and About section css is seprated
Home Page content is properly alinged

### CODE REVIEW

**Comment by dhrumishah** [comment]
The PR will not get merge cause there are some conflicts as shown here:
image


Also, I'm not able to see Project and Blog Section. And in the Home page my left portion is collapsing.
image

**Comment by Chandraprakash-Darji** [comment]
You can simply resolve conflict by using GitHub cli. Instructions are given there

**Comment by Chandraprakash-Darji** [comment]
I don't think the left portion is collapsing?

**Comment by Chandraprakash-Darji** [comment]
Let me fix blog page.

**Comment by dhrumishah** [comment]
> @dhrumishah Fixed Blog page and Projects page

Thanks for your contribution :)

**Pull request merged**
