### PR TITLE
The project is restructured for scalability.

### LINKED ISSUE #5: Improve Folder Structure
Components should be in folder of compoenents and pages should be pages folder.
I will work on it

### PR DESCRIPTION
**Pull request by Chandraprakash-Darji**
fixes #5  #3
Changes that are Made:
- Navbar and Bottom arrows are in the `components` directory.
- `/About`, `/Blog`, `/Contact`, `/Intro`, and `/Project` are in the `pages` directory.
- All the images in `/public` directory.
- Navbar is only included in `App` because it is shared with the whole app it will remain the same. 
- Added favicon to the Website.
- Changed the `render()` function in `main.jsx` according to react 18.
- imported CSS only to `App` no need to include it in every file.
- Instead of using `navigate()` I changed to Link component.
- Home page is proper responsive
- Navlink has now active Link view
- Navbar is reponsive and centered to layout
- Navbar and About section css is seprated
- Home Page content is properly alinged

### CODE REVIEW

**Comment by dhrumishah** [comment]
image
 
Navbar isn't looking good.

**Comment by Chandraprakash-Darji** [comment]
I am fixing that

**Comment by Chandraprakash-Darji** [comment]
I am fixing in #4

**Comment by Chandraprakash-Darji** [comment]
@dhrumishah Done with this

**Comment by dhrumishah** [comment]
> @dhrumishah Done with this

Request for Some changes:
1. The font which you have used is good but I'll go with the previous one.
2. Use the margin in "rem" and don't go for static ones.
3. Change the design of button to previous one.

Now the NavBar looks good also I've seen you've changed the logo. That's awesome. I hope you will follow these changes :)

**Comment by Chandraprakash-Darji** [comment]
Why you closed it ?

**Comment by dhrumishah** [comment]
> Why you closed it ?

cause there are some bugs and netlify is not deploying it

**Pull request closed without merging**
